--- 
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "tpcw-web"
  namespace: "kube-bench"
  labels: 
    name: "tpcw-web"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "tpcw-web"
  template: 
    metadata: 
      labels: 
        name: "tpcw-web"
    spec:
      containers:
      - name: "tpcw-web"
        image: "registry.cn-beijing.aliyuncs.com/dosproj/tpcw-web:final-amd64"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tpcw-web-service
  namespace: kube-bench
  labels: 
    name: kube-web-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web-service-port
  selector:
    name: "tpcw-web"