---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bugs.doslab.io
spec:
  group: doslab.io
  names:
    kind: Bug
    plural: bugs
    shortNames:
    - bug
    singular: bug
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            

