kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: sparkclusters.radanalytics.io
spec:
  group: radanalytics.io
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: sparkclusters
    singular: sparkcluster
  scope: Namespaced
  versions: 
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              worker:
                type: object
                properties:
                  instances:
                    type: string
              master:
                type: object
                properties:
                  instances:
                    type: string
